<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="System.Net.Http.Json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\UI\TaskFlow.Uno\Views\MainPage.xaml"
             Link="Presentation\MainPage.xaml"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\src\UI\TaskFlow.Uno\Views\CategoryTreePage.xaml"
             Link="Presentation\CategoryTreePage.xaml"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\src\UI\TaskFlow.Uno\Views\TagManagementPage.xaml"
             Link="Presentation\TagManagementPage.xaml"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UI\TaskFlow.Uno.Core\TaskFlow.Uno.Core.csproj" />
    <ProjectReference Include="..\..\src\UI\TaskFlow.Uno.Presentation\TaskFlow.Uno.Presentation.csproj" />
  </ItemGroup>

</Project>
