<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Test.Unit" />
    <InternalsVisibleTo Include="Test.Architecture" />
    <InternalsVisibleTo Include="TaskFlow.Api" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EF.Common.Contracts" />
    <PackageReference Include="EF.CQRS" />
    <PackageReference Include="EF.Data.Contracts" />
    <PackageReference Include="EF.Storage.Contracts" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Application.Contracts\TaskFlow.Application.Contracts.csproj" />
    <ProjectReference Include="..\TaskFlow.Application.Mappers\TaskFlow.Application.Mappers.csproj" />
    <ProjectReference Include="..\TaskFlow.Application.Models\TaskFlow.Application.Models.csproj" />
    <ProjectReference Include="..\..\Domain\TaskFlow.Domain.Model\TaskFlow.Domain.Model.csproj" />
    <ProjectReference Include="..\..\Domain\TaskFlow.Domain.Shared\TaskFlow.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\Shared\TaskFlow.Observability\TaskFlow.Observability.csproj" />
  </ItemGroup>

</Project>
