server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /app-config.json {
        alias /var/cache/nginx/app-config/app-config.json;
        add_header Cache-Control "no-store" always;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
