using Refit;
using TaskFlow.Domain.Shared.Enums;

namespace TaskFlow.ApiClient;

/// <summary>
/// Hand-written companion to the Refitter-generated <see cref="ITaskFlowApiClient"/>
/// (ITaskFlowApiClient.Generated.cs, regenerated by docs/plans/client-generation.md), split out as its
/// own interface rather than a second partial of ITaskFlowApiClient.
///
/// POST /api/v1/attachments/upload binds an actual file part (server-side: <c>IFormFile file</c>,
/// AttachmentEndpoints.Upload) alongside scalar form fields. Two separate problems rule out putting this
/// on ITaskFlowApiClient:
/// 1. OpenAPI describes the file part as a `multipart/form-data` schema property of type "string, format:
///    binary" - Refitter's --interface-only generation recognizes the [Multipart] shape for the scalar
///    fields (see the generated, unused <c>UploadAttachment</c> method) but drops the file part entirely,
///    so that generated method can never actually upload a file.
/// 2. A correct multipart method using <see cref="StreamPart"/> is a request shape the Refit *source
///    generator* cannot build (RF006) - it needs the reflection-based request builder. ITaskFlowApiClient
///    is registered via AddRefitGeneratedClient (source-generated, AOT/trim-friendly - relevant for the
///    Uno WASM head) for its other 31 methods, so this one method is isolated on its own small interface
///    registered via AddRefitClient (reflection) instead of forcing reflection onto the whole client.
/// </summary>
public interface IAttachmentUploadClient
{
    /// <summary>Uploads a file Attachment. The "file" parameter name must match the server's IFormFile parameter for model binding to succeed.</summary>
    [Multipart]
    [Post("/api/v1/attachments/upload")]
#pragma warning disable RF006 // StreamPart multipart uploads are unsupported by Refit's source generator
                              // (github.com/reactiveui/refit issue tracking generator multipart parity).
                              // This interface is deliberately registered via the reflection-based
                              // AddRefitClient, never AddRefitGeneratedClient, so the fallback the
                              // analyzer warns about is the intended code path. Remove this pragma if a
                              // future Refit version's generator supports StreamPart.
    Task<DefaultResponseOfAttachmentDto> UploadAttachmentAsync(
        StreamPart file,
        [AliasAs("ownerType")] AttachmentOwnerType ownerType,
        [AliasAs("ownerId")] Guid ownerId,
        [AliasAs("id")] Guid? id = null,
        CancellationToken cancellationToken = default);
#pragma warning restore RF006
}
