// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using TaskFlow.Application.Models;
using TaskFlow.Application.Models.Paging;
using TaskFlow.Application.Models.Reads;
using TaskFlow.Domain.Shared.Enums;
using EF.Common.Contracts;

#nullable enable annotations

namespace TaskFlow.ApiClient
{
    /// <summary>TaskFlow API</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ITaskFlowApiClient
    {
        /// <summary>Search Categories with paging, filters, and sorts</summary>
        /// <param name="includeTotal">includeTotal parameter</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/categories/search")]
        Task<PagedResponseOfCategoryDto> SearchCategories([Query] bool? includeTotal, [Body] SearchRequestOfCategorySearchFilter body, CancellationToken cancellationToken = default);

        /// <summary>Get a single Category</summary>
        /// <param name="id">id parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/categories/{id}")]
        Task<DefaultResponseOfCategoryDto> GetCategory(System.Guid id, CancellationToken cancellationToken = default);

        /// <summary>Update an existing Category</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/categories/{id}")]
        Task<DefaultResponseOfCategoryDto> UpdateCategory(System.Guid id, [Body] DefaultRequestOfCategoryDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Delete a Category</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/categories/{id}")]
        Task DeleteCategory(System.Guid id, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Create a new Category</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/categories")]
        Task<DefaultResponseOfCategoryDto> CreateCategory([Body] DefaultRequestOfCategoryDto body, CancellationToken cancellationToken = default);

        /// <summary>Search Tags with paging, filters, and sorts</summary>
        /// <param name="includeTotal">includeTotal parameter</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/tags/search")]
        Task<PagedResponseOfTagDto> SearchTags([Query] bool? includeTotal, [Body] SearchRequestOfTagSearchFilter body, CancellationToken cancellationToken = default);

        /// <summary>Get a single Tag</summary>
        /// <param name="id">id parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/tags/{id}")]
        Task<DefaultResponseOfTagDto> GetTag(System.Guid id, CancellationToken cancellationToken = default);

        /// <summary>Update an existing Tag</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/tags/{id}")]
        Task<DefaultResponseOfTagDto> UpdateTag(System.Guid id, [Body] DefaultRequestOfTagDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Delete a Tag</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/tags/{id}")]
        Task DeleteTag(System.Guid id, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Create a new Tag</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/tags")]
        Task<DefaultResponseOfTagDto> CreateTag([Body] DefaultRequestOfTagDto body, CancellationToken cancellationToken = default);

        /// <summary>Search TaskItems with keyset (cursor) paging, filters, and a sort mode</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/task-items/search")]
        Task<CursorPageOfTaskItemDto> SearchTaskItems([Body] TaskItemCursorSearchRequest body, CancellationToken cancellationToken = default);

        /// <summary>Get a single TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/task-items/{id}")]
        Task<DefaultResponseOfTaskItemDto> GetTaskItem(System.Guid id, CancellationToken cancellationToken = default);

        /// <summary>Update an existing TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/task-items/{id}")]
        Task<DefaultResponseOfTaskItemDto> UpdateTaskItem(System.Guid id, [Body] DefaultRequestOfTaskItemDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Partially update a TaskItem (JSON merge patch - omitted fields are unchanged)</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Patch("/api/v1/task-items/{id}")]
        Task<DefaultResponseOfTaskItemDto> PatchTaskItem(System.Guid id, [Body] DefaultRequestOfTaskItemPatchDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Delete a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/task-items/{id}")]
        Task DeleteTaskItem(System.Guid id, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Create a new TaskItem (optional caller-supplied UUIDv7 id makes it idempotent)</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/task-items")]
        Task<DefaultResponseOfTaskItemDto> CreateTaskItem([Body] DefaultRequestOfTaskItemDto body, CancellationToken cancellationToken = default);

        /// <summary>Add a Comment to a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/task-items/{id}/comments")]
        Task<DefaultResponseOfCommentDto> AddTaskItemComment(System.Guid id, [Body] DefaultRequestOfCommentDto body, CancellationToken cancellationToken = default);

        /// <summary>Update a Comment on a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="commentId">commentId parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/task-items/{id}/comments/{commentId}")]
        Task<DefaultResponseOfCommentDto> UpdateTaskItemComment(System.Guid id, System.Guid commentId, [Body] DefaultRequestOfCommentDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Remove a Comment from a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="commentId">commentId parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/task-items/{id}/comments/{commentId}")]
        Task RemoveTaskItemComment(System.Guid id, System.Guid commentId, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Add a ChecklistItem to a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/task-items/{id}/checklist-items")]
        Task<DefaultResponseOfChecklistItemDto> AddTaskItemChecklistItem(System.Guid id, [Body] DefaultRequestOfChecklistItemDto body, CancellationToken cancellationToken = default);

        /// <summary>Update a ChecklistItem on a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="checklistItemId">checklistItemId parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/task-items/{id}/checklist-items/{checklistItemId}")]
        Task<DefaultResponseOfChecklistItemDto> UpdateTaskItemChecklistItem(System.Guid id, System.Guid checklistItemId, [Body] DefaultRequestOfChecklistItemDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Remove a ChecklistItem from a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="checklistItemId">checklistItemId parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/task-items/{id}/checklist-items/{checklistItemId}")]
        Task RemoveTaskItemChecklistItem(System.Guid id, System.Guid checklistItemId, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Associate a Tag with a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="tagId">tagId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json")]
        [Post("/api/v1/task-items/{id}/tags/{tagId}")]
        Task<DefaultResponseOfTaskItemTagDto> AssociateTaskItemTag(System.Guid id, System.Guid tagId, CancellationToken cancellationToken = default);

        /// <summary>Remove a Tag association from a TaskItem</summary>
        /// <param name="id">id parameter</param>
        /// <param name="tagId">tagId parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/task-items/{id}/tags/{tagId}")]
        Task RemoveTaskItemTag(System.Guid id, System.Guid tagId, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Search Attachments with paging, filters, and sorts</summary>
        /// <param name="includeTotal">includeTotal parameter</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/attachments/search")]
        Task<PagedResponseOfAttachmentDto> SearchAttachments([Query] bool? includeTotal, [Body] SearchRequestOfAttachmentSearchFilter body, CancellationToken cancellationToken = default);

        /// <summary>Get a single Attachment</summary>
        /// <param name="id">id parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json")]
        [Get("/api/v1/attachments/{id}")]
        Task<DefaultResponseOfAttachmentDto> GetAttachment(System.Guid id, CancellationToken cancellationToken = default);

        /// <summary>Update an existing Attachment</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json, application/json", "Content-Type: application/json")]
        [Put("/api/v1/attachments/{id}")]
        Task<DefaultResponseOfAttachmentDto> UpdateAttachment(System.Guid id, [Body] DefaultRequestOfAttachmentDto body, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Delete an Attachment</summary>
        /// <param name="id">id parameter</param>
        /// <param name="if_Match">Aggregate version from the resource's ETag, or * to overwrite unconditionally.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>Precondition Failed</description>
        /// </item>
        /// <item>
        /// <term>428</term>
        /// <description>Precondition Required</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/problem+json")]
        [Delete("/api/v1/attachments/{id}")]
        Task DeleteAttachment(System.Guid id, [Header("If-Match")] string if_Match, CancellationToken cancellationToken = default);

        /// <summary>Create a new Attachment</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json, application/problem+json", "Content-Type: application/json")]
        [Post("/api/v1/attachments")]
        Task<DefaultResponseOfAttachmentDto> CreateAttachment([Body] DefaultRequestOfAttachmentDto body, CancellationToken cancellationToken = default);

        /// <summary>Upload a file Attachment</summary>
        /// <param name="ownerType">ownerType parameter</param>
        /// <param name="ownerId">ownerId parameter</param>
        /// <param name="id">id parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict</description>
        /// </item>
        /// </list>
        /// </exception>
        [Multipart]
        [Headers("Accept: application/json, application/problem+json")]
        [Post("/api/v1/attachments/upload")]
        Task<DefaultResponseOfAttachmentDto> UploadAttachment(AttachmentOwnerType? ownerType, System.Guid? ownerId, System.Guid? id, CancellationToken cancellationToken = default);

        /// <summary>Tenant task counts by status, overdue, and total in one round trip</summary>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/api/v1/task-items/summary")]
        Task<TaskItemSummaryDto> GetTaskItemSummary(CancellationToken cancellationToken = default);

        /// <summary>Stream the tenant's tasks as newline-delimited JSON, resumable by afterId</summary>
        /// <param name="afterId">afterId parameter</param>
        /// <param name="batchSize">batchSize parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/x-ndjson, application/problem+json")]
        [Get("/api/v1/task-items/export")]
        Task<TaskItemExportDto> ExportTaskItems([Query] System.Guid? afterId, [Query] int? batchSize, CancellationToken cancellationToken = default);

        /// <summary>Full category and tag lists for pickers</summary>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/api/v1/task-metadata")]
        Task<TaskMetadataDto> GetTaskMetadata(CancellationToken cancellationToken = default);

    }


}