<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <MSTestParallelizeAssembly>false</MSTestParallelizeAssembly>
    <MSTestParallelizeTestClasses>false</MSTestParallelizeTestClasses>
    <StartupObject>Test.PlaywrightUI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.Support\Test.Support.csproj" />
    <ProjectReference Include="..\..\src\Host\Aspire\AppHost\AppHost.csproj" AdditionalProperties="SkipUnoWasmBuild=true" />
    <ProjectReference Include="..\..\src\Host\TaskFlow.Uno.WasmHost\TaskFlow.Uno.WasmHost.csproj" AdditionalProperties="SkipUnoWasmBuild=true" />
  </ItemGroup>

</Project>
