<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <MSTestParallelizeAssembly>false</MSTestParallelizeAssembly>
    <MSTestParallelizeTestClasses>false</MSTestParallelizeTestClasses>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Appium.WebDriver" />
    <PackageReference Include="EF.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
