<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>EF.Messaging.RabbitMq.Tests</RootNamespace>
    <AssemblyName>EF.Messaging.RabbitMq.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Packages\EF.Messaging.RabbitMq\EF.Messaging.RabbitMq.csproj" />
  </ItemGroup>

</Project>
