<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Test.Unit" />
    <InternalsVisibleTo Include="TaskFlow.Bootstrapper" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EF.Common" />
    <PackageReference Include="EF.Common.Contracts" />
    <PackageReference Include="EF.Storage.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Application.Contracts\TaskFlow.Application.Contracts.csproj" />
    <ProjectReference Include="..\TaskFlow.Application.Mappers\TaskFlow.Application.Mappers.csproj" />
    <ProjectReference Include="..\TaskFlow.Application.Models\TaskFlow.Application.Models.csproj" />
    <ProjectReference Include="..\..\Domain\TaskFlow.Domain.Model\TaskFlow.Domain.Model.csproj" />
    <ProjectReference Include="..\..\Shared\TaskFlow.Observability\TaskFlow.Observability.csproj" />
  </ItemGroup>

</Project>
