// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TaskFlow.Infrastructure.Data;

#nullable disable

namespace TaskFlow.Infrastructure.Data.Migrations.PostgreSql.Migrations.TaskFlow
{
    [DbContext(typeof(TaskFlowDbContextTrxn))]
    [Migration("20260908232538_AddTaskItemEmbedding")]
    partial class AddTaskItemEmbedding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("taskflow")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Domain.Model.Attachment", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "OwnerType", "OwnerId", "Id")
                        .HasDatabaseName("IX_Attachment_TenantId_OwnerType_OwnerId_Id");

                    b.ToTable("Attachment", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_TenantId_Name");

                    b.HasIndex("TenantId", "ParentCategoryId");

                    b.ToTable("Category", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.ChecklistItem", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "TaskItemId", "Id")
                        .HasDatabaseName("IX_ChecklistItem_TenantId_TaskItemId_Id");

                    b.ToTable("ChecklistItem", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Comment", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "TaskItemId", "Id")
                        .HasDatabaseName("IX_Comment_TenantId_TaskItemId_Id");

                    b.ToTable("Comment", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Tag", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tag_TenantId_Name");

                    b.ToTable("Tag", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Features")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextOccurrenceAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OccurrenceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OverdueNotifiedForDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentTaskItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecurrenceTemplateId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("SecureDeterministic")
                        .HasMaxLength(256)
                        .HasColumnType("bytea")
                        .HasAnnotation("TaskFlow:BlindIndex", "SecureDeterministicBlindIndex");

                    b.Property<byte[]>("SecureDeterministicBlindIndex")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SecureRandom")
                        .HasMaxLength(256)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TerminalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "NextOccurrenceAtUtc")
                        .HasDatabaseName("IX_TaskItem_TenantId_NextOccurrenceAtUtc");

                    b.HasIndex("TenantId", "ParentTaskItemId");

                    b.HasIndex("TenantId", "SecureDeterministicBlindIndex")
                        .HasDatabaseName("IX_TaskItem_TenantId_SecureDeterministicBlindIndex");

                    b.HasIndex("TenantId", "CategoryId", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_CategoryId_Id");

                    b.HasIndex("TenantId", "DueDate", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_DueDate_Id");

                    b.HasIndex("TenantId", "ModifiedAtUtc", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_ModifiedAtUtc_Id");

                    b.HasIndex("TenantId", "Priority", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_Priority_Id");

                    b.HasIndex("TenantId", "RecurrenceTemplateId", "OccurrenceUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskItem_TenantId_RecurrenceTemplateId_OccurrenceUtc");

                    b.HasIndex("TenantId", "Status", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_Status_Id");

                    b.HasIndex("TenantId", "TerminalAtUtc", "Status")
                        .HasDatabaseName("IX_TaskItem_TenantId_TerminalAtUtc_Status");

                    b.HasIndex("TenantId", "Title", "Id")
                        .HasDatabaseName("IX_TaskItem_TenantId_Title_Id");

                    b.ToTable("TaskItem", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItemTag", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "TagId");

                    b.HasIndex("TenantId", "TaskItemId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskItemTag_TenantId_TaskItemId_TagId");

                    b.ToTable("TaskItemTag", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.Operational.AuditLogRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ElapsedTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<long>("StartTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("TenantId", "RecordedUtc", "Id");

                    b.HasIndex("RecordedUtc")
                        .HasDatabaseName("IX_AuditLog_RecordedUtc");

                    b.ToTable("AuditLog", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.Operational.BlobDeleteWork", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseToken")
                        .HasDatabaseName("IX_BlobDeleteWork_LeaseToken");

                    b.HasIndex("DeadLetteredAtUtc", "AvailableAtUtc", "LeaseExpiresUtc")
                        .HasDatabaseName("IX_BlobDeleteWork_Dispatch");

                    b.ToTable("BlobDeleteWork", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.Operational.ConsumerInbox", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Consumer", "MessageId");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_ConsumerInbox_ProcessedAtUtc");

                    b.ToTable("ConsumerInbox", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.Operational.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseToken")
                        .HasDatabaseName("IX_OutboxMessage_LeaseToken");

                    b.HasIndex("DeadLetteredAtUtc", "AvailableAtUtc", "LeaseExpiresUtc")
                        .HasDatabaseName("IX_OutboxMessage_Dispatch");

                    b.ToTable("OutboxMessage", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.ReadModel.TaskItemEmbedding", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "TaskItemId");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("IX_TaskItemEmbedding_Embedding_Hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("TaskItemEmbedding", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Infrastructure.Data.ReadModel.TaskViewRecord", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ChecklistCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("ChecklistTotal")
                        .HasColumnType("integer");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SubTaskCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "LastModifiedUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_TaskView_TenantId_LastModifiedUtc_Id");

                    b.ToTable("TaskView", "taskflow");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("TenantId", "ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.ChecklistItem", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TenantId", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Comment", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("Comments")
                        .HasForeignKey("TenantId", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Category", "Category")
                        .WithMany("TaskItems")
                        .HasForeignKey("TenantId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "ParentTaskItem")
                        .WithMany("SubTasks")
                        .HasForeignKey("TenantId", "ParentTaskItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("TaskFlow.Domain.Model.ValueObjects.RecurrencePattern", "RecurrencePattern", b1 =>
                        {
                            b1.Property<Guid>("TaskItemTenantId");

                            b1.Property<Guid>("TaskItemId");

                            b1.Property<DateTimeOffset?>("EndDate");

                            b1.Property<string>("Frequency")
                                .IsRequired();

                            b1.Property<int>("Interval");

                            b1.HasKey("TaskItemTenantId", "TaskItemId");

                            b1.ToTable("TaskItem", "taskflow");

                            b1
                                .ToJson("RecurrencePattern")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemTenantId", "TaskItemId");
                        });

                    b.Navigation("Category");

                    b.Navigation("ParentTaskItem");

                    b.Navigation("RecurrencePattern");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItemTag", b =>
                {
                    b.HasOne("TaskFlow.Domain.Model.Tag", "Tag")
                        .WithMany("TaskItemTags")
                        .HasForeignKey("TenantId", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.Domain.Model.TaskItem", "TaskItem")
                        .WithMany("TaskItemTags")
                        .HasForeignKey("TenantId", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.Tag", b =>
                {
                    b.Navigation("TaskItemTags");
                });

            modelBuilder.Entity("TaskFlow.Domain.Model.TaskItem", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("Comments");

                    b.Navigation("SubTasks");

                    b.Navigation("TaskItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
